//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ServiceModel;
using System.Runtime.Serialization;


namespace DatabaseService
{
    [DataContract]
    public class BetaTester
    {
        [DataMember]
        public virtual int ID
        {
            get;
            set;
        }

        [DataMember]
        public virtual string Name
        {
            get;
            set;
        }

        [DataMember]

        public virtual string Email
        {
            get;
            set;
        }

        [DataMember]

        public virtual string IP
        {
            get;
            set;
        }

        [DataMember]

        public virtual DateTime RegistrationDate
        {
            get;
            set;
        }

        [DataMember]
        public virtual string Code
        {
            get;
            set;
        }

        //private string _name;
        //private string _email;
        //private string _ip;
        //private DateTime _registrationDate;
        //private string _code;

        public BetaTester()
        {

        }

        public BetaTester(string name, string email, string ip, string code, DateTime registerDate)
        {
            //_name = name;
            //_email = email;
            //_ip = ip;
            //_code = code;
            //_registrationDate = registerDate;

            Name = name;
            Email = email;
            IP = ip;
            Code = code;
            RegistrationDate = registerDate;
        }       
    }

}