//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ServiceModel;
using System.Data;


namespace DatabaseService
{

    [ServiceContract(SessionMode=SessionMode.Required, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign)]    
    public interface IDatabaseService
    {
        [OperationContract]        
        bool Login(string password);        

        /// <summary>
        /// Receives the beta testers table from MS-SQL database
        /// </summary>
        /// <returns>DataTable</returns>
        //[OperationContract(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign)]
        [OperationContract]
        [FaultContract(typeof(DatabaseServiceException))]
        DataTable GetBetaTestersTable();

        [OperationContract]
        void AddNewBetaTester(BetaTester bt);

        [OperationContract]
        void DeleteBetaTester(BetaTester bt);

        [OperationContract]
        void AddNewCustomer(Customer cs);

        [OperationContract]
        void DeleteCustomer(Customer cs);

        [OperationContract]
        DataTable GetCustomersTable();

        [OperationContract]
        void UpdateCustomersTable(DataTable table);

        [OperationContract]
        void UpdateBetaTestersTable(DataTable table);

        [OperationContract]
        bool CheckTesterExists(string name, string mail, string ip);
    }

}